### ISSUE TITLE
Add LLVM 14 binaries

### ISSUE THREAD

**Issue by inorick** [muttleyxd/clang-tools-static-binaries#16]
It would be nice to have static builds for the latest release:
https://github.com/llvm/llvm-project/releases/tag/llvmorg-14.0.0

**Comment by muttleyxd** [comment]
Fixed by: https://github.com/muttleyxd/clang-tools-static-binaries/releases/tag/master-208096c1

Feel free to reopen, leave a comment or create a new issue if there's a problem with new release.
