### ISSUE TITLE
AUR package clang-format-static-bin outdated 

### ISSUE THREAD

**Issue by Xhendos** [muttleyxd/clang-tools-static-binaries#29]
Hey muttleyxd,

I noticed that you are the maintainer of the [clang-format-static-bin](https://aur.archlinux.org/packages/clang-format-static-bin) AUR package. In the ```PKGBUILD``` I saw that it uses links to this repository, which frankly enough, is your own repository. I've seen that you updated this repository to ```clang-format-16``` which is fairly nice because since version 16 of ```clang-format``` the ```AlignTrailingComments```  option is not simply a boolean anymore, but has various options (see screenshot below) which I need for a codebase that I am maintaining. 

Could you please also update the ```PKGBUILD``` of the AUR package? In the meantime I'll run ```clang-format``` version 16 manually from this repository thus outside of my AUR package manager.

![Untitled](https://github.com/muttleyxd/clang-tools-static-binaries/assets/16403693/338e52d4-fa48-4e7c-981f-81e65cea8bef)

**Comment by muttleyxd** [comment]
Hi @Xhendos, done, thanks for notifying me - I forgot about AUR. I think I may develop a pipeline for automatic AUR releases 

Feel free to reopen if issue persists
