### ISSUE TITLE
Please add clang-tools 18 binaries

### ISSUE THREAD

**Issue by alemuntoni** [muttleyxd/clang-tools-static-binaries#39]
Clang 18 [has been released](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.2), but there are no binary downloads available yet on this repository. Would it be possible to create a new release with Clang 18 binaries included?

**Comment by davidwinter** [comment]
@muttleyxd is this project still maintained? I'd be happy to submit a pull request.

**Comment by echoix** [comment]
> @muttleyxd is this project still maintained? I'd be happy to submit a pull request.

There was a pull request merged two months ago, but no new release yet https://github.com/muttleyxd/clang-tools-static-binaries/issues/40

**Comment by davidwinter** [comment]
@echoix I was hoping to use the binaries from this repo to work with a plugin for the proto tool. As it seems like this repo has gone stale, I've created a new one based off of this. It includes v18 binaries, and support for macOS on Apple Silicon, as well as the mentioned proto plugins. Feel free to check it out and use, and I welcome any feedback.

https://github.com/davidwinter/static-clang-tools-binaries

@muttleyxd Very happy to submit a pull request back to this repo if activity picks up again with the changes I've made, and perhaps if co-maintainer(s) could be added to keep it alive. The original work here is fantastic and much appreciated.

**Comment by muttleyxd** [comment]
Well, I'm quite busy, probably will be in foreseeable future, though I'd be happy to review and merge any PRs you send me.

I'll try to improve the speed of releasing new builds.

Anyways, closing this one as done. Just released the build from two months ago :sweat_smile:

**Comment by echoix** [comment]
Thanks a lot! Does your GitHub workflows already prepare a release draft? Would you need a bit more automation to prevent situations like this from happening?

**Comment by muttleyxd** [comment]
Yeah, they do. Only left part would be waiting for it to finish, upload license files to it (IDK why I didn't store them in the repo yet) and release it to the public

**Comment by echoix** [comment]
You mean that you manually wait for the workflows to finish building (like 6h, so next day) and have go back afterwards to publish it? 

Is there some other manual steps that are needed to do for a normal release? (The goal being only merging a PR would be enough work for a release)

**Comment by muttleyxd** [comment]
> You mean that you manually wait for the workflows to finish building (like 6h, so next day) and have go back afterwards to publish it?

Yeah, I guess it's a decision from time where I created this repo - I wasn't sure of the quality and how it will all go, so I wanted to have the last "say" before releasing things. But now we definitely could switch to automatic releases.

> Is there some other manual steps that are needed to do for a normal release? (The goal being only merging a PR would be enough work for a release)

AFAIK no, here's what I think we would need to change:
- push the license files (if you have time for MR, you can find these license files under any release) to the repo
- make them get pushed to every release at the end
- verify if all steps before passed
- publish the draft release
