### ISSUE TITLE
[REQUEST] clang-tidy too?

### ISSUE THREAD

**Issue by mattgodbolt** [muttleyxd/clang-tools-static-binaries#4]
Thanks for this invaluable resource! Would it be possible to add `clang-tidy` too? And maybe some of the other clang tools (`clang-query` maybe?)

**Comment by muttleyxd** [comment]
It should be pretty simple thing to do, unless the build is so slow, that it hits 6 hour limit. I'll take a look at it :smile:

**Comment by muttleyxd** [comment]
I didn't have much time recently, so it took a while :grin:
Anyways, closed by 22538c6.

https://github.com/muttleyxd/clang-tools-static-binaries/releases/tag/master-22538c65

Feel free to reopen or post a new issue if you need more tools.
