### ISSUE TITLE
clang-format fails to run on macOS 10.15.7

### ISSUE THREAD

**Issue by gzauhar** [muttleyxd/clang-tools-static-binaries#9]
Hi there!

First of all thank you for doing this. I am using Windows and Linux binaries without any issue. But running `clang-format` on macOS gives this issue:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
$ xcodebuild -version
Xcode 12.4
Build version 12D4e
$ ./clang-format-12_macosx-amd64 
dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Users/test/Downloads/./clang-format-12_macosx-amd64
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___emutls_get_address
  Referenced from: /Users/test/Downloads/./clang-format-12_macosx-amd64
  Expected in: /usr/lib/libSystem.B.dylib

Killed: 9
```

**Comment by muttleyxd** [comment]
Hey,

it seems we made a mistake with recent refactor of CI yaml files - there is a reference to libstdc++ from GCC compiler. For now you can use this release - it's lacking clang-11 and clang-12, but it should work on any recent Mac OS X.

https://github.com/muttleyxd/clang-tools-static-binaries/releases/tag/master-22538c65

I'll ping you when new release is ready.

**Comment by muttleyxd** [comment]
@gzauhar 

Here's a new release with possible fix for this issue. Please test and let me know if it worked. It looks okay - `otool -L` doesn't list any dependency to GCC, so it should work on your machine.
https://github.com/muttleyxd/clang-tools-static-binaries/releases/tag/master-a37b22cd

**Comment by gzauhar** [comment]
Works as expected. Thank you!

**Comment by WolleTD** [comment]
I fail to see how this dependency got introduced. Was there something like your new fix in the jobs before that I haven't seen? Or does this relate to the GCC update? Then it would look like an honest CMake issue for me.

**Comment by muttleyxd** [comment]
> I fail to see how this dependency got introduced. Was there something like your new fix in the jobs before that I haven't seen? Or does this relate to the GCC update? Then it would look like an honest CMake issue for me.

Yup, looks like CMake issue - probably some new "implicit" library linked by GCC, which CMake hasn't caught up yet to, but I'm quite busy recently and can't spend much time to debug this and report it properly.
